version: '3'

tasks:
  format: gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -race
  default:
    cmds:
    - task: format
    - task: lint
    - go build sqlettus/main.go
    - task: test